-- Policy Areas based on Congress.gov taxonomy
INSERT INTO public.policy_areas (code, name, description) VALUES
('agriculture', 'Agriculture and Food', 'Farming, food safety, nutrition programs'),
('animals', 'Animals', 'Wildlife protection, animal welfare'),
('armed_forces', 'Armed Forces and National Security', 'Military, defense policy, veterans'),
('arts_culture', 'Arts, Culture, Religion', 'Arts funding, cultural affairs'),
('civil_rights', 'Civil Rights and Liberties', 'Constitutional rights, discrimination'),
('commerce', 'Commerce', 'Business regulation, consumer protection'),
('congress', 'Congress', 'Congressional operations, rules'),
('crime', 'Crime and Law Enforcement', 'Criminal justice, law enforcement'),
('economics', 'Economics and Public Finance', 'Budget, taxes, economic policy'),
('education', 'Education', 'K-12, higher education, student loans'),
('emergency', 'Emergency Management', 'Disaster response, FEMA'),
('energy', 'Energy', 'Oil, gas, renewable energy, utilities'),
('environment', 'Environmental Protection', 'EPA, pollution, conservation'),
('families', 'Families', 'Child welfare, family policy'),
('finance', 'Finance and Financial Sector', 'Banking, securities, insurance'),
('foreign_trade', 'Foreign Trade and International Finance', 'Trade agreements, tariffs'),
('government', 'Government Operations and Politics', 'Federal agencies, elections'),
('health', 'Health', 'Healthcare, Medicare, Medicaid, public health'),
('housing', 'Housing and Community Development', 'Housing policy, urban development'),
('immigration', 'Immigration', 'Border security, visas, citizenship'),
('indian_affairs', 'Native Americans', 'Tribal affairs, Indian policy'),
('international', 'International Affairs', 'Foreign policy, diplomacy'),
('labor', 'Labor and Employment', 'Wages, workplace safety, unions'),
('law', 'Law', 'Courts, legal system, judiciary'),
('public_lands', 'Public Lands and Natural Resources', 'Parks, forests, mining'),
('science', 'Science, Technology, Communications', 'Research, NASA, telecom'),
('social_welfare', 'Social Welfare', 'Social Security, welfare programs'),
('sports', 'Sports and Recreation', 'Sports policy, recreation'),
('taxation', 'Taxation', 'Tax policy, IRS'),
('transportation', 'Transportation and Public Works', 'Roads, aviation, transit'),
('water', 'Water Resources Development', 'Water infrastructure, flood control')
ON CONFLICT (code) DO NOTHING;
