-- US States and Territories
INSERT INTO public.states (code, name, region, fips_code) VALUES
('AL', 'Alabama', 'Southeast', '01'),
('AK', 'Alaska', 'West', '02'),
('AZ', 'Arizona', 'Southwest', '04'),
('AR', 'Arkansas', 'Southeast', '05'),
('CA', 'California', 'West', '06'),
('CO', 'Colorado', 'West', '08'),
('CT', 'Connecticut', 'Northeast', '09'),
('DE', 'Delaware', 'Northeast', '10'),
('FL', 'Florida', 'Southeast', '12'),
('GA', 'Georgia', 'Southeast', '13'),
('HI', 'Hawaii', 'West', '15'),
('ID', 'Idaho', 'West', '16'),
('IL', 'Illinois', 'Midwest', '17'),
('IN', 'Indiana', 'Midwest', '18'),
('IA', 'Iowa', 'Midwest', '19'),
('KS', 'Kansas', 'Midwest', '20'),
('KY', 'Kentucky', 'Southeast', '21'),
('LA', 'Louisiana', 'Southeast', '22'),
('ME', 'Maine', 'Northeast', '23'),
('MD', 'Maryland', 'Northeast', '24'),
('MA', 'Massachusetts', 'Northeast', '25'),
('MI', 'Michigan', 'Midwest', '26'),
('MN', 'Minnesota', 'Midwest', '27'),
('MS', 'Mississippi', 'Southeast', '28'),
('MO', 'Missouri', 'Midwest', '29'),
('MT', 'Montana', 'West', '30'),
('NE', 'Nebraska', 'Midwest', '31'),
('NV', 'Nevada', 'West', '32'),
('NH', 'New Hampshire', 'Northeast', '33'),
('NJ', 'New Jersey', 'Northeast', '34'),
('NM', 'New Mexico', 'Southwest', '35'),
('NY', 'New York', 'Northeast', '36'),
('NC', 'North Carolina', 'Southeast', '37'),
('ND', 'North Dakota', 'Midwest', '38'),
('OH', 'Ohio', 'Midwest', '39'),
('OK', 'Oklahoma', 'Southwest', '40'),
('OR', 'Oregon', 'West', '41'),
('PA', 'Pennsylvania', 'Northeast', '42'),
('RI', 'Rhode Island', 'Northeast', '44'),
('SC', 'South Carolina', 'Southeast', '45'),
('SD', 'South Dakota', 'Midwest', '46'),
('TN', 'Tennessee', 'Southeast', '47'),
('TX', 'Texas', 'Southwest', '48'),
('UT', 'Utah', 'West', '49'),
('VT', 'Vermont', 'Northeast', '50'),
('VA', 'Virginia', 'Southeast', '51'),
('WA', 'Washington', 'West', '53'),
('WV', 'West Virginia', 'Southeast', '54'),
('WI', 'Wisconsin', 'Midwest', '55'),
('WY', 'Wyoming', 'West', '56'),
('DC', 'District of Columbia', 'Northeast', '11'),
('PR', 'Puerto Rico', 'Southeast', '72'),
('GU', 'Guam', 'West', '66'),
('VI', 'Virgin Islands', 'Southeast', '78'),
('AS', 'American Samoa', 'West', '60'),
('MP', 'Northern Mariana Islands', 'West', '69')
ON CONFLICT (code) DO NOTHING;
